# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "account_types", :force => true do |t|
    t.column "name", :string, :limit => 100, :default => "", :null => false
  end

  create_table "accounts", :force => true do |t|
    t.column "name",            :string,  :limit => 100, :default => "", :null => false
    t.column "user_id",         :integer,                                :null => false
    t.column "parent_id",       :integer
    t.column "deleteLock",      :integer, :limit => 1
    t.column "parentLock",      :integer, :limit => 1
    t.column "account_type_id", :integer,                                :null => false
  end

  create_table "accounts_groups", :id => false, :force => true do |t|
    t.column "account_id", :integer, :null => false
    t.column "group_id",   :integer, :null => false
  end

  create_table "alert_parameter_types", :force => true do |t|
    t.column "name", :string, :limit => 100
  end

  create_table "alert_parameters", :force => true do |t|
    t.column "alert_id",                :integer
    t.column "value",                   :string,  :limit => 100
    t.column "alert_parameter_type_id", :integer
  end

  create_table "alert_types", :force => true do |t|
    t.column "subject",  :string, :limit => 100
    t.column "body",     :string, :limit => 1000
    t.column "function", :string, :limit => 50
  end

  create_table "alerts", :force => true do |t|
    t.column "alert_type_id", :integer
    t.column "user_id",       :integer
    t.column "email",         :string,  :limit => 250
  end

  create_table "events", :force => true do |t|
    t.column "user_id",    :integer,                                :null => false
    t.column "name",       :string,  :limit => 150, :default => "", :null => false
    t.column "moment",     :date,                                   :null => false
    t.column "isEstimate", :integer, :limit => 1
  end

  create_table "events_accounts", :force => true do |t|
    t.column "amount",     :decimal,              :precision => 12, :scale => 2, :null => false
    t.column "event_id",   :integer,                                             :null => false
    t.column "account_id", :integer,                                             :null => false
    t.column "is_credit",  :integer, :limit => 1,                                :null => false
  end

  create_table "groups", :force => true do |t|
    t.column "name",    :string,  :limit => 100, :default => "", :null => false
    t.column "user_id", :integer,                                :null => false
  end

  create_table "user_accounts", :force => true do |t|
    t.column "user_id",     :integer,              :null => false
    t.column "account_id",  :integer,              :null => false
    t.column "permissions", :integer, :limit => 1
    t.column "isLink",      :integer, :limit => 1
  end

  create_table "users", :force => true do |t|
    t.column "name",             :string,   :limit => 100
    t.column "email",            :string,   :limit => 100
    t.column "login",            :string,   :limit => 50
    t.column "crypted_password", :string,   :limit => 40
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "activated_at",     :datetime
    t.column "activation_code",  :string,   :limit => 40
    t.column "salt",             :string,   :limit => 40
    t.column "level",            :integer,  :limit => 1
  end

end
